M2 features
Zondax/ledger-penumbra pull request #19
Opened 2024-12-23 19:46 UTC by abenso

Parser and UI Implementation
- Parameters
- Memo
- Spend
- Output
- Swap
- ICS-20 Withdrawal

Effect hash computation
Spend authorization signature
Updated icons

2024-12-24 11:31 UTC, chcmedeiros approved these changes

2024-12-24 13:00 UTC, emmanuelm41 commented
On crypto.c, I see we are caching the keys, but I don't see where we unset the cache
```
if (!fvk_cached_set) {
        // Compute seed
        CATCH_ZX_ERROR(computeSpendKey(&keys));

        // use seed to compute viewieng keys
        CATCH_ZX_ERROR(compute_keys(&keys));

        // Copy keys
        CATCH_ZX_ERROR(copyKeys(&keys, Fvk, output, len, cmdResponseLen));

        MEMCPY(fvk_cached, keys.fvk, FVK_LEN);

        fvk_cached_set = true;
    } else {
        MEMCPY(output, fvk_cached, FVK_LEN);
    }
```

2024-12-24 13:01 UTC, emmanuelm41 commented
On coin.h, the ticket is "penumbra". I think it should be UM 

```
#define COIN_TICKER "penumbra"
```

2024-12-24 13:08 UTC, emmanuelm41 commented
On ICS20 transfers, are we holding a list of supported tokens, or anything like that? I wonder how we handling amount formatting, and tickers

2024-12-24 13:15 UTC, emmanuelm41 commented
On zemu tests, for show address randomized, on flex/stax we see "sub account # 1" when the device allows you to display it as a QR code... later you see the address. Is that correct? It seems a bit weird

2024-12-24 13:17 UTC, emmanuelm41 commented
For unknown assets, what we usually do is to display the asset id in a different page, not in the same where the fee value is displayed. It is a bit hard to read the fee alongside with the token asset id (taken from zemu images to)

2024-12-24 13:17 UTC, neithanmo commented
> On zemu tests, for show address randomized, on flex/stax we see "sub account # 1" when the device allows you to display it as a QR code... later you see the address. Is that correct? It seems a bit weird


Yes, that was a request from them, to display sub-account #address_index

2024-12-24 13:19 UTC, neithanmo commented
> For unknown assets, what we usually do is to display the asset id in a different page, not in the same where the fee value is displayed. It is a bit hard to read the fee alongside with the token asset id (taken from zemu images to)


I think the same, but that is the specific UI they requested in the test vectors
like everything in the same line.

2024-12-24 13:19 UTC, emmanuelm41 commented
From past experience, I think we will need to leave the unknown asset ids under expert mode, as ledger won't accept those long asset ids as clear signing. If expert mode is not enabled, we should reject the tx with a specific error

2024-12-24 13:21 UTC, emmanuelm41 requested changes
left some comments

2024-12-24 13:40 UTC, neithanmo commented on app/Makefile.version
> -APPVERSION_P=2
indeed, i will bump it to 0.1.0

2024-12-26 15:32 UTC, emmanuelm41 approved these changes

2024-12-26 15:32 UTC, merged